export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS";
export const GET_NOTIFICATIONS_ERROR = "GET_NOTIFICATIONS_ERROR";

export const POST_NOTIFICATION_SUCCESS = "POST_NOTIFICATION_SUCCESS";
export const POST_NOTIFICATION_ERROR = "POST_NOTIFICATION_ERROR";

