export const GET_SUBSCRIBERS = "GET_SUBSCRIBERS";
export const CREATE_SUBSCRIBER_SUCCESS = "CREATE_SUBSCRIBER_SUCCESS";
export const CREATE_SUBSCRIBER_ERROR = "CREATE_SUBSCRIBER_ERROR";
export const DELETE_SUBSCRIBER_SUCCESS = "DELETE_SUBSCRIBER_SUCCESS";
export const DELETE_SUBSCRIBER_ERROR = "DELETE_SUBSCRIBER_ERROR";